# Generated by Django 5.0.6 on 2024-07-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='car_description',
            new_name='Book_description',
        ),
    ]
