# Generated by Django 5.0.6 on 2024-07-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_rename_car_description_book_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='book',
        ),
    ]
