# Generated by Django 5.0.6 on 2024-07-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
