# Generated by Django 5.0.6 on 2024-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_image',
            field=models.ImageField(upload_to='book/media/uploads/'),
        ),
    ]
