# Generated by Django 5.0.6 on 2024-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_alter_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
